### ISSUE TITLE
Parameters - language specific

### ISSUE THREAD

**Issue by bjbakker1984** [aaronparker/Intune#1]
I found that on Dutch laptops, the script didn't work. 
I changed the following to make the scripts (both Scheduled Task script and Redirect script) more "international": 

old: 
    [Parameter()]$Group = "BUILTIN\Users",

new: 
    [Parameter()]$Group = ".\" + (Get-LocalGroup -SID S-1-5-32-545).Name,

Regards,

Jeroen

**Comment by aaronparker** [comment]
Excellent. Thank-you, will update ASAP.__

**Comment by aaronparker** [comment]
Redirect-Folders.ps1 is now updated and should work on non-English language OS. I've only tested so far on an English language OS, but querying for the group name via SID works as expected.
